
import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { AiFillTwitterCircle, AiFillLinkedin } from "react-icons/ai";
import { GiHamburgerMenu } from "react-icons/gi";
import Image from "next/image";
import benoy from "../public/assets/benoy.jpg";
import design from "../public/assets/design.png";
import code from "../public/assets/code.png";
import consulting from "../public/assets/consulting.png";
import web1 from "../public/assets/web1.png";
import web2 from "../public/assets/web2.png";
import web3 from "../public/assets/web3.png";
import web4 from "../public/assets/web4.png";
import web5 from "../public/assets/web5.png";
import web6 from "../public/assets/web6.png";
import netflix from '../public/assets/netflix.png';
import { useRef, useState, useEffect } from "react";
import styles from "../styles/parallax.module.css";
import { BsChevronUp } from 'react-icons/bs';
import { FaSquarePhone } from "react-icons/fa6";

export default function Home() {
  const [darkMode, setDarkMode] = useState(true);
  const [menuOpen, setMenuOpen] = useState(false);
  const [scrollY, setScrollY] = useState(0);
  const [isVisible, setIsVisible] = useState(false);
  const dropdownRef = useRef(null);

  useEffect(() => {
    // Add scroll event listener to show/hide the button
    const handleScroll = () => {
      if (window.scrollY > 300) {
        setIsVisible(true);
      } else {
        setIsVisible(false);
      }
    };

    window.addEventListener('scroll', handleScroll);

    // Remove event listener on component unmount
    return () => {
      window.removeEventListener('scroll', handleScroll);
    };
  }, []);

  const scrollToTop = () => {
    window.scrollTo({
      top: 0,
      behavior: 'smooth',
    });
  };

  const toggleDarkMode = () => {
    setDarkMode(!darkMode);
  };

  const toggleMenuOpen = () => {
    setMenuOpen(!menuOpen);
  };

  useEffect(() => {
    const handleScroll = () => {
      setScrollY(window.scrollY);
    };

    window.addEventListener("scroll", handleScroll);

    return () => {
      window.removeEventListener("scroll", handleScroll);
    };
  }, []);

  const handleLinkClick = () => {
    setMenuOpen(false);
  };

  const translateY = -scrollY * 0.5; // Adjust the multiplier to control the parallax speed

  return (
    <div className={darkMode ? "dark " : ""}>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="px-10 md:px-20 lg:px-30 dark:bg-gray-900 bg-gray-100">
        {/* go up button */}
        <button
          className={`fixed bottom-4 right-4 bg-gray-800 text-white p-3 rounded-full shadow-lg transition-opacity duration-300 ${isVisible ? 'opacity-100' : 'opacity-0'}`}
          onClick={scrollToTop}
          aria-label="Scroll to top"
        >
          <BsChevronUp className="text-2xl" />
        </button>

        <section className="min-h-screen">

          <div className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons dark:text-white">developedby Judy</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  className="cursor-pointer text-2xl dark:text-white"
                  onClick={toggleDarkMode}
                />
              </li>
              <li>
                <a href="#" className="bg-gradient-to-r from-cyan-500 to-teal-500 shadow-sm bg-cyan-500 text-white px-4 py-2 rounded-md ml-8 animate-pulse">
                  Resume
                </a>
              </li>
              <li>
                <GiHamburgerMenu
                  className={`text-4xl ml-8 dark:text-white cursor-pointer transition-transform duration-100 ${menuOpen ? 'transform rotate-180' : ''}`}
                  onClick={toggleMenuOpen}
                />
              </li>
            </ul>
          </div>

          {menuOpen && (
            <div ref={dropdownRef} className="absolute top-24 right-16 bg-white dark:bg-gray-600 shadow-lg rounded-lg py-4 px-6 w-44 z-50 transition-all duration-300 transform origin-top-right" style={{ transform: menuOpen ? 'scaleY(1)' : 'scaleY(0)' }}>
              <ul className="flex flex-col space-y-4">
                <li>
                  <a href="#Tools and tech" className="dark:text-white" onClick={handleLinkClick}>Tools and Tech</a>
                </li>
                <li>
                  <a href="#projects" className="dark:text-white" onClick={handleLinkClick}>Projects</a>
                </li>
                <li>
                  <a href="#contact" className="dark:text-white" onClick={handleLinkClick}>Contact</a>
                </li>
              </ul>
            </div>
          )}

          <div className={`parallax ${styles.parallax}`} style={{ transform: `translateY(${translateY}px)` }}>
            <div className="text-center p-10 py-8">
              <h2 className="text-5xl py-2 text-teal-500 font-normal font-serif md:text-6xl">I'M Benoy Judy,</h2>
              <h3 className="text-2xl py-2 dark:text-white md:text-3xl">React Developer based in Kerala</h3>
              <p className="text-md py-3 leading-8 text-gray-700 dark:text-gray-400  md:text-xl max-w-lg mx-auto ">Freelancer providing services for programming and design content needs. Join me and let's get cracking!!</p>
            </div>
            <div className="flex text-4xl text-gray-500 py-2 pb-4 justify-center gap-6">
              <AiFillLinkedin />
              <AiFillTwitterCircle />
              <FaSquarePhone />
            </div>
            <div className="relative bg-gradient-to-b from-teal-600 rounded-full w-80 h-80 mx-auto overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={benoy} alt="developer Benoy" objectFit="cover" />
            </div>

          </div>


        </section>

        {/* 2nd section */}
        < section id="Tools and tech">
          <div className="dark:text-white">
            <h3 className="text-3xl py-2 font-semibild">
              My Tools and Technology
            </h3>
            <p className="text-md py-2 leading-8 ">simply dummy text of the <span className="text-teal-500">printing and typesetting industry</span> Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
            <p className="text-md py-2 leading-8 "> I offer wide range of services including brand design ,programming and teaching.</p>
          </div>

          <div className="lg:flex gap-10 ">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white">
              <Image src={design} width={100} height={100} />
              <h3 className="text-lg font-md pt-8 pb-2">Beautiful Designs</h3>
              <p className="py-2"> Creating elegant designs suited for your needs </p>
              <h4 className=" text-teal-600 py-4">Design tools I use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Photoshop</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white">
              <Image src={code} width={100} height={100} />
              <h3 className="text-lg font-md pt-8 pb-2">Beautiful Designs</h3>
              <p className="py-2"> Creating elegant designs suited for your needs </p>
              <h4 className=" text-teal-600 py-4">Design tools I use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Photoshop</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white">
              <Image src={consulting} width={100} height={100} />
              <h3 className="text-lg font-md pt-8 pb-2">Beautiful Designs</h3>
              <p className="py-2"> Creating elegant designs suited for your needs </p>
              <h4 className=" text-teal-600 py-4">Design tools I use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Photoshop</p>
            </div>

          </div>
        </section >

        {/* 3rd section */}
        < section id="projects" >
          <div className="dark:text-white">
            <h3 className="text-3xl py-1">
              Latest projects
            </h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-white ">is simply dummy text of the <span className="text-teal-500">printing and typesetting industry</span> Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-white"> I offer wide range of services including brand design ,programming and teaching.</p>
          </div>

          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 relative over "><a href="https://netflix-ai-one.vercel.app/" target="_blank" rel="noopener noreferrer"><Image src={netflix} className="rounded-lg " objectFit="cover" width={"100%"} height={"100%"} layout="responsive" /></a></div>
            <div className="basis-1/3 flex-1 relative over"><Image src={web1} className="rounded-lg p-2" objectFit="cover" width={"100%"} height={"100%"} layout="responsive" /></div>
            <div className="basis-1/3 flex-1 relative over"><Image src={web3} className="rounded-lg" objectFit="cover" width={"100%"} height={"100%"} layout="responsive" /></div>
            <div className="basis-1/3 flex-1 relative over"><Image src={web4} className="rounded-lg" objectFit="cover" width={"100%"} height={"100%"} layout="responsive" /></div>


          </div>

        </section >
      </main >
    </div >
  );
}
